### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by michael-morris** [JeffreyHyer/bamboohr-laravel#1]
Can support 5.6.*? Love the non Laravel library, working on a new Laravel based project would love to continue to use your BambooHR package.

**Comment by JeffreyHyer** [comment]
Yeah we can do that. I'll add support for Laravel 5.6 shortly (next couple of days).

**Comment by JeffreyHyer** [comment]
OK, should be good to go. Let me know if you run into any issues using this package with Laravel 5.6 :+1:
