### ISSUE TITLE
$response->hasErrors() returning false even if the calls return 503

### ISSUE THREAD

**Issue by kszyrvercobrador** [JeffreyHyer/bamboohr-laravel#2]
I try to request using to bamboohr api using wrong subdomain and key.

`$response->getCode()`
returns 503

but when I do
`$response->hasErros()`
returns false

**Comment by JeffreyHyer** [comment]
@kszyrvercobrador the `hasErrors()` method is a shortcut to access the error message(s) returned from BambooHR in the HTTP headers. In your case a 503 error doesn't have any error messages so there are no errors to return.

In practice, you should use both `getCode()` and `hasErrors()` to determine if the request was successful.

If you're interested in the details you can see the implementation of [`hasErrors()`](https://github.com/JeffreyHyer/bamboohr/blob/master/src/Api/Response.php#L25) and [`getErrors()`](https://github.com/JeffreyHyer/bamboohr/blob/master/src/Api/Response.php#L30). The real work happens here: [`_getErrors()`](https://github.com/JeffreyHyer/bamboohr/blob/master/src/Api/Response.php#L50)
